trigger: none
pool: humarapool
stages:
  - stage: terraformInitvalidate
    displayName: Terraform Init or validate karo
    jobs:
      - job: TerraformInitValidate
        displayName: Terraform Init and validate karna hai
        steps:
          - task: TerraformTask@5
            displayName: terraform init bhai
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'hamara-sc'
              backendAzureRmStorageAccountName: 'narottamstorageacct12346'
              backendAzureRmContainerName: 'mycontainer'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            displayName: terraform validate
            inputs:
              provider: 'azurerm'
              command: 'validate'
      - job: TerraformPlan
        displayName: terraform init or plan

        steps:
        
          - task: TerraformTask@5
            displayName: terraform init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'hamara-sc'
              backendAzureRmStorageAccountName: 'narottamstorageacct12346'
              backendAzureRmContainerName: 'mycontainer'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            displayName: terraform plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'hamara-sc'
      - job: scanning
        displayName: scan karna hai bhai tfsec se
        steps:
          