trigger: none
pool: humarapool
stages:
  - stage: terraformInitvalidate
    displayName: Terraform Init or validate karo
    jobs:
      - job: TerraformInitValidate
        displayName: Terraform Init and validate karna hai
        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'hamara-sc'
              backendAzureRmStorageAccountName: 'narottamstorageacct12346'
              backendAzureRmContainerName: 'mycontainer'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'validate'
      - job: TerraformPlan

        steps:
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'hamara-sc'
              backendAzureRmStorageAccountName: 'narottamstorageacct12346'
              backendAzureRmContainerName: 'mycontainer'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTask@5
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'hamara-sc'